//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token is required..
        /// </summary>
        public static string VALIDATION_ACCESS_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_ACCESS_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You must add at least one ingredient..
        /// </summary>
        public static string VALIDATION_AT_LEAST_ONE_INGREDIENT {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LEAST_ONE_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You must add at least one instruction..
        /// </summary>
        public static string VALIDATION_AT_LEAST_ONE_INSTRUCTION {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LEAST_ONE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The selected preparation time is invalid..
        /// </summary>
        public static string VALIDATION_COOK_TIME_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_COOK_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The current password is incorrect..
        /// </summary>
        public static string VALIDATION_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One of the selected dish types is invalid..
        /// </summary>
        public static string VALIDATION_DISH_TYPE_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_DISH_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  This email is already in use..
        /// </summary>
        public static string VALIDATION_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid email address..
        /// </summary>
        public static string VALIDATION_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email is required..
        /// </summary>
        public static string VALIDATION_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ingredient cannot be empty..
        /// </summary>
        public static string VALIDATION_INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ingredient must have a maximum of 250 characters..
        /// </summary>
        public static string VALIDATION_INGREDIENT_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_INGREDIENT_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The instruction description must have a maximum of 2,000 characters..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The instruction description is mandatory..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The instruction order must be greater than 0..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_ORDER_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_ORDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid email or password.
        /// </summary>
        public static string VALIDATION_LOGIN_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is required..
        /// </summary>
        public static string VALIDATION_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passwor must be at least 6 characters long..
        /// </summary>
        public static string VALIDATION_PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password is required.
        /// </summary>
        public static string VALIDATION_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You do not have access to this feature..
        /// </summary>
        public static string VALIDATION_RESOURCE_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("VALIDATION_RESOURCE_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title must be at most 250 characters..
        /// </summary>
        public static string VALIDATION_TITLE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_TITLE_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title is required..
        /// </summary>
        public static string VALIDATION_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_TITLE_REQUIRED", resourceCulture);
            }
        }
    }
}
